GET http://localhost:8000/games
###
GET http://localhost:8000/games/
###
POST http://localhost:8000/games
Content-Type: application/json

{
    "name":"",
    "company":"",
    "console":"",
    "release":""
}
###
PATCH http://localhost:8000/games/
Content-Type: application/json

{
    "name":"",
    "company":"",
    "console":"",
    "release":""
}
###
PUT http://localhost:8000/games/
Content-Type: application/json

{
    "name":"",
    "company":"",
    "console":"",
    "release":""
}
###
DELETE http://localhost:8000/games/
###
OPTIONS http://localhost:8000/games
###
OPTIONS http://localhost:8000/games/